-- Database Tables (MySQL) for Locker Access Management System

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50),
    password VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lockers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    locker_number VARCHAR(100) NOT NULL UNIQUE,
    size ENUM('SMALL', 'MEDIUM', 'LARGE') NOT NULL,
    branch VARCHAR(255) NOT NULL,
    status ENUM('AVAILABLE', 'ASSIGNED', 'MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE',
    assigned_to BIGINT,
    FOREIGN KEY (assigned_to) REFERENCES customers(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS officers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    branch VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS access_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    locker_id BIGINT NOT NULL,
    requested_date DATE NOT NULL,
    requested_time_slot VARCHAR(100) NOT NULL,
    purpose TEXT,
    status ENUM('PENDING', 'CUSTOMER_VERIFIED', 'OFFICER_VERIFIED', 'COMPLETED', 'CANCELLED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
    entry_time DATETIME,
    exit_time DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    FOREIGN KEY (locker_id) REFERENCES lockers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS otps (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reference_id BIGINT NOT NULL,
    otp_type ENUM('CUSTOMER_ACCESS', 'OFFICER_AUTH', 'REGISTRATION', 'TAMPER_REPORT') NOT NULL,
    otp_code VARCHAR(20) NOT NULL,
    is_used BOOLEAN DEFAULT FALSE,
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tamper_reports (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    locker_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    reported_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    status ENUM('OPEN', 'RESOLVED') NOT NULL DEFAULT 'OPEN',
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    FOREIGN KEY (locker_id) REFERENCES lockers(id) ON DELETE CASCADE
);
